/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "AuthFn": {
      "publicKey": string
      "type": "sst.aws.Auth"
    }
    "WebApp": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
    "dashboard": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
  }
}
