/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "ApiRouter": {
      "type": "sst.aws.Router"
      "url": string
    }
    "AppDb": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "AuthApiDomain": {
      "type": "sst.aws.Router"
      "url": string
    }
    "AuthFn": {
      "publicKey": string
      "type": "sst.aws.Auth"
    }
    "AuthFnAuthenticator": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "KvStore": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "RestApi": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "TrpcApi": {
      "type": "sst.aws.Router"
      "url": string
    }
    "TrpcApiFn": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
  }
}
